version: 1
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make codegen
builds:
  - binary: pulumi-resource-opnsense
    dir: provider
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/oss4u/pulumi-opnsense/provider/Version={{.Tag }}
    main: ./cmd/pulumi-resource-opnsense/
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
