// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"example.com/pulumi-opnsense/sdk/go/opnsense/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The address of the fw. (without /api)
func GetAddress(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:address")
}

// The key to access the api of the fw.
func GetKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:key")
}

// The secret to access the api of the fw.
func GetSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:secret")
}
