# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('opnsense')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def address(self) -> Optional[str]:
        """
        The address of the fw. (without /api)
        """
        return __config__.get('address')

    @_builtins.property
    def key(self) -> Optional[str]:
        """
        The key to access the api of the fw.
        """
        return __config__.get('key')

    @_builtins.property
    def secret(self) -> Optional[str]:
        """
        The secret to access the api of the fw.
        """
        return __config__.get('secret')

