name: develop
on:
  push:
    branches:
      - develop

env:
  PROVIDER: "opnsense"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    strategy:
      fail-fast: true
      matrix:
        goversion:
          - 1.20.x
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Semver
        id: release
        uses: cocogitto/cocogitto-action@v3.5
#      - name: Unshallow clone for tags
#        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.goversion}}
          cache: true
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: pulumi/pulumictl
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v4
#        with:
#          distribution: goreleaser
#          args: release --clean --snapshot --skip-publish
#          version: latest