name: main
on:
  push:
    branches:
      - main

env:
  PROVIDER: "opnsense"
  # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  version:
    runs-on: ubuntu-latest
    name: version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Semver release
        id: release
        uses: cocogitto/cocogitto-action@v3.5
        with:
          release: true
          git-user: 'version'
          git-user-email: 'info@sys-int.de'